spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost/PRUEBAS_VOTOS?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=${POSTGRES_DB_SCHEMA:public}
spring.datasource.hikari.schema=${POSTGRES_DB_SCHEMA:public}
